# Generated by Django 5.2.3 on 2025-06-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
