# Generated by Django 5.2.3 on 2025-06-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0003_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='historico_medico',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
