# Generated by Django 5.2.3 on 2025-06-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0004_paciente_cpf_paciente_historico_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='historico_medico',
        ),
        migrations.AddField(
            model_name='paciente',
            name='convenio',
            field=models.CharField(default='Particular', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default='sememail@teste.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
