# Generated by Django 5.2.3 on 2025-06-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0006_prontuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='descricao',
        ),
        migrations.AddField(
            model_name='prontuario',
            name='diagnostico',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prontuario',
            name='prescricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
