# Generated by Django 5.2.3 on 2025-06-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0007_remove_prontuario_descricao_prontuario_diagnostico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
