# Generated by Django 5.2.3 on 2025-06-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0008_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
