# Generated by Django 5.2.3 on 2025-06-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0009_alter_profissional_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
    ]
