# Generated by Django 5.2.3 on 2025-07-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0011_alter_consulta_descricao_alter_consulta_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
    ]
